"""empty message

Revision ID: 27be99b8a3ee
Revises: 07c4598038d3
Create Date: 2023-08-15 17:36:33.670545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27be99b8a3ee'
down_revision = '07c4598038d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('active')

    # ### end Alembic commands ###
