"""empty message

Revision ID: 843b4dbc0a74
Revises: 27be99b8a3ee
Create Date: 2023-08-16 02:48:41.365258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '843b4dbc0a74'
down_revision = '27be99b8a3ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.alter_column('comment',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('date_posted',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.alter_column('date_posted',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('comment',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)

    # ### end Alembic commands ###
